[package]
name = "coins"
version = "1.0.0"
authors = ["Yash Sharma <iamyxsh@icloud.com>"]

[addresses]
dextr_test = "0xe907d546f3e08358303d5ed0c23ed5daee1aa96e4e2ffabd4db22c5eaa464ac1"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dev-dependencies]
